name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra latexmk
          sudo apt-get install -y texlive-lang-chinese

      - name: Build LaTeX document using Makefile
        run: make all

      - name: Move PDF to artifacts directory
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts

      - name: Move to deploy directory
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy

      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true

  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME
